language: cpp

dist: trusty

apt:
  addons:
    sources:
      - george-edison55-cmake-3.x
    packages:
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

script:
  - ctest -V -S cmake/TestVecCore.cmake
